# Generated by Django 3.2.6 on 2022-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='get_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pd', 'pending'), ('bk', 'booked'), ('vs', 'visited')], default='pd', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('bs', 'Business'), ('rx', 'Relax'), ('wd', 'Wild'), ('mx', 'Mixed'), ('in', 'International')], default='mx', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_night',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
