# Generated by Django 3.2.6 on 2022-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='_msg',
            field=models.TextField(blank=True),
        ),
    ]
