# Generated by Django 3.2.6 on 2022-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20220321_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stuffs',
            field=models.ManyToManyField(blank=True, to='events.Stuff'),
        ),
    ]
