# Generated by Django 3.2.6 on 2022-04-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_enrollment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='_pointer',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='op',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='_pointer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='voterp',
            name='_pointer',
        ),
        migrations.RemoveField(
            model_name='voterp',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VoteRp',
        ),
    ]
