# Generated by Django 3.2.6 on 2022-04-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pt',
        ),
    ]
