# Generated by Django 3.2.6 on 2022-04-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1020)),
                ('seat', models.IntegerField(default=40)),
                ('type', models.CharField(choices=[('ac', 'AC'), ('nonac', 'Non AC'), ('Sleeper', 'Sleeper')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available', models.IntegerField(default=44)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.buses')),
            ],
        ),
    ]
