# Generated by Django 3.2.6 on 2022-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fair',
            field=models.FloatField(default=500.0),
        ),
    ]
