# Generated by Django 3.2.6 on 2022-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_buses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
