# Generated by Django 3.2.6 on 2022-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hotelreservation_hotelreview_roommodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='hotelName',
            field=models.CharField(choices=[('Pan_Pacific_Sonargoan', 'Pan Pacific Sonargoan'), ('Radisson_Blu', 'Radisson Blu'), ('Hotel_De_Meridian', 'Hotel De Meridian'), ('Grand_Plaza_Hotel', 'Grand Plaza Hotel'), ('Empyrean_Hotel', 'Empyrean Hotel'), ('The_Raintree_Dhaka', 'The Raintree Dhaka')], default=None, max_length=100, null=True),
        ),
    ]
