# Generated by Django 3.2.6 on 2022-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='PlaceName',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Barisal', 'Barisal'), ('Cumilla', 'Cumilla'), ('Cox_Bazar', 'Cox-Bazar'), ('Rangamati', 'Rangamati'), ('Bandarban', 'Bandarban'), ('Khagrachori', 'Khagrachori'), ('Moynamoti', 'Moynamoti'), ('Sylhet', 'Sylhet'), ('Gazipur', 'Gazipur'), ('Rajshahi', 'Rajshahi')], default=None, max_length=100, null=True, unique=True),
        ),
    ]
